name: Tests

# Trigger the workflow on push to main/develop and on all pull requests
on:
  push:
    branches: [main, master, recette, cicd/**]
  pull_request:
    branches: [main, master, recette]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        